name: pytorch3
channels:
  - anaconda
  - intel
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - antspyx==0.3
  - cudatoolkit=11.3
  - dateparser=1.0
  - gensim=4.1
  - matplotlib=3.5
  - nibabel=3.2
  - nltk=3.5
  - numpy=1.21
  - optuna=2.10
  - pandas=1.4
  - pydicom=2.3
  - python=3.9
  - pytorch=1.11
  - scikit-learn=1.0
  - scipy=1.7
  - seaborn=0.11
  - setuptools=58.0
  - tensorboard=2.8
  - torchaudio=0.11
  - torchvision=0.12
  - tqdm=4.63
  - pip:
      - click==8.0
      - monai==0.8
      - spacy==3.1
